# Generated by Django 4.1.4 on 2024-05-01 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 9, 19, 48, 159198, tzinfo=datetime.timezone.utc)),
        ),
    ]
