# Generated by Django 4.1.4 on 2024-05-01 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0002_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 9, 21, 41, 798406, tzinfo=datetime.timezone.utc)),
        ),
    ]
