# Generated by Django 4.1.4 on 2024-06-24 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0003_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 24, 22, 35, 41, 499675, tzinfo=datetime.timezone.utc)),
        ),
    ]
