# Generated by Django 4.1.4 on 2024-05-11 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0004_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 10, 8, 47, 695315, tzinfo=datetime.timezone.utc)),
        ),
    ]
