# Generated by Django 4.1.4 on 2024-05-11 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0005_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 11, 14, 9, 357515, tzinfo=datetime.timezone.utc)),
        ),
    ]
