# Generated by Django 4.1.4 on 2023-12-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(default='Abidjan', max_length=50)),
                ('tauxODP', models.CharField(default='6', max_length=50)),
                ('tauxTSP', models.CharField(default='7', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeCollectee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(blank=True, max_length=50)),
                ('Marque', models.CharField(blank=True, max_length=50)),
                ('commune', models.CharField(blank=True, max_length=50)),
                ('type_support', models.CharField(blank=True, max_length=50)),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('surfaceODP', models.CharField(blank=True, max_length=50)),
                ('canal', models.CharField(blank=True, max_length=50)),
                ('etat_support', models.CharField(blank=True, max_length=50)),
                ('typesite', models.CharField(blank=True, max_length=50)),
                ('visibilite', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('observation', models.CharField(blank=True, max_length=50)),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('image_support', models.ImageField(blank=True, null=True, upload_to='collecte_images/')),
                ('duree', models.CharField(blank=True, max_length=50)),
                ('TSP', models.CharField(blank=True, default=12, max_length=50)),
                ('ODP', models.BooleanField(blank=True, default=False)),
                ('ODP_value', models.CharField(blank=True, default=1, max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupportPublicitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_support', models.CharField(max_length=50)),
                ('longueur', models.CharField(max_length=50)),
                ('largeur', models.CharField(max_length=50)),
                ('taux', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibilite', models.CharField(max_length=50)),
            ],
        ),
    ]
