# Generated by Django 4.1.4 on 2023-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeCollectee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50)),
                ('Marque', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('type_support', models.CharField(max_length=50)),
                ('surface', models.FloatField()),
                ('surfaceODP', models.FloatField(max_length=50)),
                ('canal', models.CharField(max_length=50)),
                ('etat_support', models.CharField(max_length=50)),
                ('visibilite', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('observation', models.CharField(max_length=50)),
                ('date_collecte', models.DateTimeField(auto_now_add=True)),
                ('image_support', models.ImageField(blank=True, null=True, upload_to='collecte_images/')),
                ('duree', models.FloatField()),
                ('TSP', models.FloatField()),
                ('ODP', models.BooleanField(default=False)),
                ('ODP_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupportPublicitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_support', models.CharField(max_length=50)),
                ('longueur', models.CharField(max_length=50)),
                ('largeur', models.CharField(max_length=50)),
                ('taux', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibilite', models.CharField(max_length=50)),
            ],
        ),
    ]
