# Generated by Django 4.1.4 on 2023-10-08 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneecollectee',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='support_publicitaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supportpublicitaire'),
        ),
    ]
