# Generated by Django 4.1.4 on 2023-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
