# Generated by Django 4.1.4 on 2023-11-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='latitude',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='longitude',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
    ]
