# Generated by Django 4.1.4 on 2023-12-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxODP',
            field=models.CharField(blank=True, default=6, max_length=50),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxTSP',
            field=models.CharField(blank=True, default=6, max_length=50),
        ),
    ]
