# Generated by Django 4.1.4 on 2024-05-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TTAP', models.CharField(max_length=50)),
                ('TTPAT', models.CharField(max_length=50)),
                ('TAE', models.CharField(max_length=50)),
                ('TAEAT', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='TAE',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='TAEAT',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='TTAP',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='TTPAT',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
