# Generated by Django 4.1.4 on 2023-11-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='surfaceODP',
            field=models.FloatField(),
        ),
    ]
