# Generated by Django 4.1.4 on 2024-05-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportpublicitaire',
            old_name='largeur',
            new_name='surface',
        ),
        migrations.RemoveField(
            model_name='supportpublicitaire',
            name='longueur',
        ),
        migrations.RemoveField(
            model_name='supportpublicitaire',
            name='taux',
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='quartier',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marque',
            name='surface',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
