# Generated by Django 4.1.4 on 2024-05-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(default='Abidjan', max_length=50)),
                ('quartier', models.CharField(default='Rue 12', max_length=50)),
            ],
        ),
    ]
