# Generated by Django 4.1.4 on 2023-10-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='largeur',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='longueur',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
