# Generated by Django 4.1.4 on 2024-06-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxAE',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxAEA',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxAET',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxAP',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxAPA',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='tauxAPT',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
