# Generated by Django 4.1.4 on 2024-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
