# Generated by Django 4.1.4 on 2024-06-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_donneecollectee_tauxae_donneecollectee_tauxaea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='nom1',
            new_name='Rcontact',
        ),
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='nom2',
            new_name='Rnom',
        ),
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='nom3',
            new_name='Rprenom',
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='Scontact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='Snom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='Sprenom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='signature1',
            field=models.ImageField(blank=True, null=True, upload_to='collecte_images/'),
        ),
    ]
