# Generated by Django 4.1.4 on 2023-10-08 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_donneecollectee_largeur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneecollectee',
            name='proprietaire',
        ),
    ]
