# Generated by Django 4.1.4 on 2023-11-05 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_donneecollectee_surfaceodp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='ODP_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='TSP',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='agent',
            field=models.ForeignKey(blank=True, default='issa@gmail.com', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
