# Generated by Django 4.1.4 on 2023-10-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_canal_etat_marque_site_visibilite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='support_publicitaire',
            new_name='type_support',
        ),
    ]
