# Generated by Django 4.1.4 on 2024-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quartier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='TAE',
            new_name='AE',
        ),
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='TAEAT',
            new_name='AEA',
        ),
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='TTAP',
            new_name='AET',
        ),
        migrations.RenameField(
            model_name='donneecollectee',
            old_name='TTPAT',
            new_name='AP',
        ),
        migrations.AddField(
            model_name='commune',
            name='tauxAE',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='tauxAEA',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='tauxAET',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='tauxAP',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='tauxAPA',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='tauxAPT',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='APA',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='APT',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
