# Generated by Django 4.1.4 on 2024-05-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_largeur_supportpublicitaire_surface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneecollectee',
            name='anciennete',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
