# Generated by Django 4.1.4 on 2023-10-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_support_publicitaire_donneecollectee_type_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneecollectee',
            name='surface',
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='largeur',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='longueur',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='observation',
            field=models.CharField(default='2', max_length=50),
            preserve_default=False,
        ),
    ]
