# Generated by Django 4.1.4 on 2024-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_donneecollectee_anciennete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='anciennete',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
