# Generated by Django 4.1.4 on 2024-05-11 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_tae_donneecollectee_ae_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(default='Abidjan', max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='donneecollectee',
            name='ville',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quartier',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quartier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
