# Generated by Django 4.1.4 on 2023-11-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_donneecollectee_latitude_donneecollectee_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='Marque',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='ODP',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='canal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='commune',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='duree',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='entreprise',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='etat_support',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='observation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='surface',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='surfaceODP',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='type_support',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='visibilite',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
