# Generated by Django 4.1.4 on 2023-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_donneecollectee_surface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='type_support',
            field=models.CharField(max_length=50),
        ),
    ]
