# Generated by Django 4.1.4 on 2023-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_donneecollectee_marque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneecollectee',
            name='agent',
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='ODP_value',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='TSP',
            field=models.FloatField(blank=True, default=12),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='latitude',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='longitude',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
