# Generated by Django 4.1.4 on 2023-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_donneecollectee_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donneecollectee',
            name='ODP_value',
            field=models.CharField(blank=True, default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='TSP',
            field=models.CharField(blank=True, default=12, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='duree',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='latitude',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='longitude',
            field=models.CharField(blank=True, default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='surface',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='donneecollectee',
            name='surfaceODP',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
